language: java


jdk:
- openjdk8

install: mvn clean install package

deploy:
  region: eu-gb
  api: https://api.eu-gb.bluemix.net
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    branch: master
