kumuluzee:
  name: dummy-consumer
  version: 1.0.0
  env:
    name: dev
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
  server:
    base-url: http://169.51.13.160 # zunanji URL
    http:
      port: 8080
  discovery:
    etcd:
      hosts: http://etcd:2379
    ttl: 20
    ping-interval: 15

rest-config:
  string-property: Monday
  boolean-property: true
  integer-property: 23

# ETCD kubernetes deployment -> github rso-customers @ jmezna