kumuluzee:
  name: dummy-consumer
  version: 1.0.0
  env:
    name: dev
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
  server:
    base-url: http://169.51.13.160 # zunanji URL
    http:
      port: 8080
  discovery:
    etcd:
      hosts: http://etcd:2379
    ttl: 20
    ping-interval: 15
  cors-filter:
    servlet:
      allow-origin: "*"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="customers">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="40ea390d-ae06-41fa-9ba3-3d426395c000-ls.logit.io" port="17078"
                                                                                         protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="info"/>
                              <AppenderRef ref="logstash" level="trace"/>
                          </Root>
                      </Loggers>
                  </Configuration>'
rest-config:
  string-property: Monday
  boolean-property: true
  integer-property: 23

# ETCD kubernetes deployment -> github rso-customers @ jmezna