apiVersion: v1
kind: ReplicationController
metadata:
  name: rso-dummy-consumer-deployment
spec:
  replicas: 1
  selector:
    app: rso-dummy-consumer
  template:
    metadata:
      labels:
        app: rso-dummy-consumer
    spec:
      containers:
      - name: rso-dummy-consumer
        image: rsostream/dummyconsumer:latest
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        imagePullPolicy: Always
