apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rso-iot-dummy-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rso-dummy-consumer
    spec:
      containers:
      - image: rsostream/dummyconsumer:latest
        name: rso-dummy-consumer
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        imagePullPolicy: Always
